version: '3.5'

services:
  web:
    build: .
    container_name: youtubeapi
    image: youtubeapi:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./:/app
    ports:
        - "8000:8000"
    restart: always
    env_file:
        - ./.env
    depends_on:
        - web-db

  web-db:
    image: postgres:12-alpine
    ports:
        - "5432:5432"
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data:rw
    env_file:
        - ./.env
volumes:
  postgres_data: