# Generated by Django 3.2 on 2022-12-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodetail',
            old_name='publishedAt',
            new_name='published_at',
        ),
    ]
