# Generated by Django 3.2 on 2022-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0002_rename_publishedat_videodetail_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail_url',
            field=models.URLField(),
        ),
    ]
