# Generated by Django 3.2 on 2022-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0003_alter_videodetail_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetail',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
