# Generated by Django 3.2 on 2022-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0004_auto_20221215_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='video_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='video_title',
            field=models.TextField(),
        ),
    ]
