# Generated by Django 3.2 on 2022-12-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0005_auto_20221215_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetail',
            name='published_at',
        ),
    ]
