# Generated by Django 3.2 on 2022-12-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0006_remove_videodetail_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='video_desc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='video_title',
            field=models.CharField(max_length=2000),
        ),
    ]
